## Using functions from scripts

One can import classes and funtions from scripts in the same folder using the name of the file in question. In this ase the file is *tools.py*. THus we do the following to import them. It is also possible to set an alias for ease of use.

In [1]:
import tools as tls

The data cleaning functions are methods of the **data_cleaner** class object. Thus to use them we can create one such object and call the specific methods when they are needed.

In [2]:
cleaner = tls.data_cleaner()

### Getting climate factors 2013-2017

In [ ]:
df_rain, df_temp, df_water, df_climate_factors = cleaner.climate_factors('raw data/WORLDBANK_rainfall.csv', 'raw data/WORLDBANK_temperature.csv', 'raw data/AQUASTAT_water_resources.csv')

In [ ]:
df_climate_factors.to_csv('clean data/climate_factors.csv')
df_climate_factors

### Getting water stress indicators 2013-2017

In [ ]:
df_waterstress = cleaner.water_stress('raw data/AQUASTAT_water_stress.csv')

In [ ]:
df_waterstress.to_csv('clean data/water_stress.csv')
df_waterstress

### Getting socio economic factors

In [3]:
df_aqua, df_unicef, df_socioec_factors = cleaner.socioecon_factors('raw data/aquastat_socio_economic.csv', 'raw data/unicef_socio_economic.csv')

In [4]:
df_socioec_factors.to_csv('clean data/socioec_factors.csv')
df_socioec_factors

,Country_x,GDP per capita (current US$/inhab),Human Development Index (HDI) [highest = 1] (-),Population density (inhab/km2),Rural population (1000 inhab),Rural population with access to safe drinking-water (JMP) (%),Total population with access to safe drinking-water (JMP) (%),Urban population (1000 inhab),Urban population with access to safe drinking-water (JMP) (%),Country_y,...,"Mortality rate, infant (per 1,000 live births)","Official exchange rate (LCU per US$, period average)","PPP conversion factor, GDP (LCU per international $)","PPP conversion factor, private consumption (LCU per international $)",Population aged 25-64 years (thousands),Population growth (annual %),"Prevalence of HIV, total (% of population ages 15-49)",Price level ratio of PPP conversion factor (GDP) to market exchange rate,Total debt service (% of GNI),Total population (thousands)
0,AFG,605.557362,0.493,55.5955534111,26558.609,47.0,55.3,8971.472,78.2,AFG,...,53.2,61.92,17.246,17.48,10829.8,3.06,0.10,0.30,0.24,34346.8
1,AGO,4100.291004,0.576,23.9165524986,10472.554,28.2,49.0,19311.639,75.4,AGO,...,58.6,128.90,74.586,86.74,8732.8,3.44,1.84,0.62,7.64,27900.2
2,ALB,4445.132198,0.789,104.0089794446,1190.155,95.2,95.1,1740.032,94.9,ALB,...,8.6,116.08,42.746,53.14,1485.4,-0.20,0.10,0.34,5.74,2892.2
3,ARE,40180.344045,0.864,133.584947902,1292.709,100.0,99.6,8107.436,99.6,ARE,...,7.0,3.70,2.198,2.74,6815.8,0.74,NaN,0.60,NaN,9304.6
4,ARG,14517.291248,0.832,15.8024528845,3652.804,100.0,99.1,40618.237,99.0,ARG,...,10.2,10.84,7.162,8.12,20566.6,1.08,0.40,0.62,4.10,43070.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,VNM,2342.244006,0.69,285.6041059083,61898.302,96.9,97.6,33642.498,99.1,VNM,...,17.2,21616.82,7393.544,7855.90,49480.8,1.04,0.36,0.34,4.10,92677.0
137,WSM,4197.37637,0.706,68.785915493,160.194,99.3,99.0,36.246,97.5,WSM,...,14.6,2.48,1.672,1.88,75.2,0.66,NaN,0.68,2.68,193.4
138,YEM,854.926716,0.463,52.7204557077,18075.808,46.5,54.9,10174.612,72.0,YEM,...,43.0,227.24,93.630,90.40,9143.0,2.58,0.10,0.40,0.70,26494.2
139,ZAF,6153.459018,0.704,46.7641896825,19369.002,81.4,93.2,37348.154,99.6,ZAF,...,28.6,12.28,5.858,6.02,26332.2,1.52,19.22,0.48,4.48,55367.0
140,ZMB,1513.27609,0.589,22.3935358286,9747.709,51.3,65.4,7346.421,85.6,ZMB,...,46.6,8.00,3.466,3.54,4989.4,3.06,12.18,0.44,2.48,15884.6

## Checking countries

Need to see what country codes are shared across all datasets. The AQUA and Unicef datasets arleady have been cheked across each other. Tus can just use on of the two.

In [ ]:
set_temp = set.intersection(set(df_temp_hist['Country']), set(df_temp_proj['Country']))
set_climate = set.intersection(set(df_rain['Country']), set(df_inflow['Country']))
shared_countries = set.intersection(set_temp, set_climate, set(df_aqua['Country']))

In [ ]:
len(shared_countries)

Thus we have 135 countries that are shared across the datasets. We will write a seperate *.csv* file that includes all these countries.

In [ ]:
import pandas as pd
shared = pd.DataFrame(list(shared_countries))
shared.to_csv('shared_country_codes.csv')

### Getting projected temperatures - 2020-2039

In [ ]:
df_temp_proj = cleaner.temp_proj('raw data/tas_2020_2039_mavg_rcp26_AFG_CAF.csv')

In [ ]:
df_temp_proj.to_csv('clean data/projected_temp_2020-2039.csv')
df_temp_proj